{"name": "тест перехода по клику на «Личный кабинет»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299,560\n  (Session info: chrome=130.0.6723.69)\nStacktrace:\n#0 0x6550ed70e10a <unknown>\n#1 0x6550ed229460 <unknown>\n#2 0x6550ed211b00 <unknown>\n#3 0x6550ed2117ed <unknown>\n#4 0x6550ed20f87c <unknown>\n#5 0x6550ed21002f <unknown>\n#6 0x6550ed21f497 <unknown>\n#7 0x6550ed235474 <unknown>\n#8 0x6550ed23a7ab <unknown>\n#9 0x6550ed21073e <unknown>\n#10 0x6550ed2352d8 <unknown>\n#11 0x6550ed2b8d5b <unknown>\n#12 0x6550ed299db3 <unknown>\n#13 0x6550ed268c10 <unknown>\n#14 0x6550ed269bee <unknown>\n#15 0x6550ed6da39b <unknown>\n#16 0x6550ed6de338 <unknown>\n#17 0x6550ed6c7ebc <unknown>\n#18 0x6550ed6deeb7 <unknown>\n#19 0x6550ed6ad10f <unknown>\n#20 0x6550ed6fc828 <unknown>\n#21 0x6550ed6fc9f0 <unknown>\n#22 0x6550ed70cf86 <unknown>\n#23 0x775f9c094ac3 <unknown>", "trace": "self = <tests.test_personal_account.TestPersonalAccount object at 0x71f9500aaa70>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"2ae7cfd251dec848dfe695201912eba5\")>\nsetup = {'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjEyMWQ3OWVkMjgwMDAxYjRmY2E2NyIsImlhdCI6MTczM...XMEsDpwTF_KqW6bN6K96xBnEiHuSSSHE-NE3cBN_TI', 'email': 'oevbjogk@yandex.ru', 'name': 'hotulnga', 'password': 'hayxklck'}\n\n    @allure.title(\"тест перехода по клику на «Личный кабинет»\")\n    def test_personal_account(self, driver, setup):\n        login = Login(driver)\n>       login.login_to_profile(setup['email'], setup['password'])\n\ntests/test_personal_account.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:14: in login_to_profile\n    self.get_url(links.LINK_LOGIN)\npages/base_page.py:17: in get_url\n    self.driver.get(url)\n.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:363: in get\n    self.execute(Command.GET, {\"url\": url})\n.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x71f9500e2a70>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"timeout\",\"message\":\"timeout: Timed out receiving message from renderer: 2...\\\\n#21 0x6550ed6fc9f0 \\\\u003Cunknown>\\\\n#22 0x6550ed70cf86 \\\\u003Cunknown>\\\\n#23 0x775f9c094ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299,560\nE         (Session info: chrome=130.0.6723.69)\nE       Stacktrace:\nE       #0 0x6550ed70e10a <unknown>\nE       #1 0x6550ed229460 <unknown>\nE       #2 0x6550ed211b00 <unknown>\nE       #3 0x6550ed2117ed <unknown>\nE       #4 0x6550ed20f87c <unknown>\nE       #5 0x6550ed21002f <unknown>\nE       #6 0x6550ed21f497 <unknown>\nE       #7 0x6550ed235474 <unknown>\nE       #8 0x6550ed23a7ab <unknown>\nE       #9 0x6550ed21073e <unknown>\nE       #10 0x6550ed2352d8 <unknown>\nE       #11 0x6550ed2b8d5b <unknown>\nE       #12 0x6550ed299db3 <unknown>\nE       #13 0x6550ed268c10 <unknown>\nE       #14 0x6550ed269bee <unknown>\nE       #15 0x6550ed6da39b <unknown>\nE       #16 0x6550ed6de338 <unknown>\nE       #17 0x6550ed6c7ebc <unknown>\nE       #18 0x6550ed6deeb7 <unknown>\nE       #19 0x6550ed6ad10f <unknown>\nE       #20 0x6550ed6fc828 <unknown>\nE       #21 0x6550ed6fc9f0 <unknown>\nE       #22 0x6550ed70cf86 <unknown>\nE       #23 0x775f9c094ac3 <unknown>\n\n.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: TimeoutException"}, "steps": [{"name": "переход по клику на «Личный кабинет»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299,560\n  (Session info: chrome=130.0.6723.69)\nStacktrace:\n#0 0x6550ed70e10a <unknown>\n#1 0x6550ed229460 <unknown>\n#2 0x6550ed211b00 <unknown>\n#3 0x6550ed2117ed <unknown>\n#4 0x6550ed20f87c <unknown>\n#5 0x6550ed21002f <unknown>\n#6 0x6550ed21f497 <unknown>\n#7 0x6550ed235474 <unknown>\n#8 0x6550ed23a7ab <unknown>\n#9 0x6550ed21073e <unknown>\n#10 0x6550ed2352d8 <unknown>\n#11 0x6550ed2b8d5b <unknown>\n#12 0x6550ed299db3 <unknown>\n#13 0x6550ed268c10 <unknown>\n#14 0x6550ed269bee <unknown>\n#15 0x6550ed6da39b <unknown>\n#16 0x6550ed6de338 <unknown>\n#17 0x6550ed6c7ebc <unknown>\n#18 0x6550ed6deeb7 <unknown>\n#19 0x6550ed6ad10f <unknown>\n#20 0x6550ed6fc828 <unknown>\n#21 0x6550ed6fc9f0 <unknown>\n#22 0x6550ed70cf86 <unknown>\n#23 0x775f9c094ac3 <unknown>\n\n", "trace": "  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/pages/login_page.py\", line 14, in login_to_profile\n    self.get_url(links.LINK_LOGIN)\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/pages/base_page.py\", line 17, in get_url\n    self.driver.get(url)\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "переход по ссылке", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299,560\n  (Session info: chrome=130.0.6723.69)\nStacktrace:\n#0 0x6550ed70e10a <unknown>\n#1 0x6550ed229460 <unknown>\n#2 0x6550ed211b00 <unknown>\n#3 0x6550ed2117ed <unknown>\n#4 0x6550ed20f87c <unknown>\n#5 0x6550ed21002f <unknown>\n#6 0x6550ed21f497 <unknown>\n#7 0x6550ed235474 <unknown>\n#8 0x6550ed23a7ab <unknown>\n#9 0x6550ed21073e <unknown>\n#10 0x6550ed2352d8 <unknown>\n#11 0x6550ed2b8d5b <unknown>\n#12 0x6550ed299db3 <unknown>\n#13 0x6550ed268c10 <unknown>\n#14 0x6550ed269bee <unknown>\n#15 0x6550ed6da39b <unknown>\n#16 0x6550ed6de338 <unknown>\n#17 0x6550ed6c7ebc <unknown>\n#18 0x6550ed6deeb7 <unknown>\n#19 0x6550ed6ad10f <unknown>\n#20 0x6550ed6fc828 <unknown>\n#21 0x6550ed6fc9f0 <unknown>\n#22 0x6550ed70cf86 <unknown>\n#23 0x775f9c094ac3 <unknown>\n\n", "trace": "  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/pages/base_page.py\", line 17, in get_url\n    self.driver.get(url)\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/dim/Загрузки/Учеба/Practicum/autoqa/Diplom/Diplom_3/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/login'"}], "start": 1730224599567, "stop": 1730224899612}], "parameters": [{"name": "login_email", "value": "'oevbjogk@yandex.ru'"}, {"name": "login_password", "value": "'hayxklck'"}], "start": 1730224599567, "stop": 1730224899614}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1730224599566, "stop": 1730224899616, "uuid": "5a711ead-0039-4fde-ae3f-860c6e660a02", "historyId": "2321bd8c027fd32be744f46fa0abfe6f", "testCaseId": "52aa0dc3a4e94a479f6175e6b9231b72", "fullName": "tests.test_personal_account.TestPersonalAccount#test_personal_account", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_personal_account"}, {"name": "subSuite", "value": "TestPersonalAccount"}, {"name": "host", "value": "home"}, {"name": "thread", "value": "72351-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_personal_account"}]}